version: "3.1"
services:
  mongo:
    image: mongo:latest
    container_name: "mongo-container"
    ports:
      - 27017:27017

  cache:
    image: redis/redis-stack:latest
    restart: always
    ports:
      - "6379:6379"

  task-rest-api:
    build:
      context: .
    image: "task-api"
    environment:
      MONGO_URI: mongodb://mongo:27017/db
    depends_on:
      - cache
      - mongo
    ports:
      - 3000:3000
